title: Nico's Blog
email: nicolas@santini.nz
description: >- # this means to ignore newlines until "baseurl:"
  A place for me to share things I come across with. And also original thoughts and ideas
  that come from my learning experiences.
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: 'https://santini.nz' # the base hostname & protocol for your site, e.g. http://example.com
github_username: nsantini
theme: minima
